name: Проверка страницы Twitch Drops

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run check script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python3 check_twitchdrops.py

      - name: Commit updated page content (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add twitchdrops.html || true
          if ! git diff --cached --quiet; then
            git commit -m "ci: update twitchdrops.html"
            git push
          else
            echo "No changes to commit"
          fi
